export const ALL_CART_REQUEST = 'ALL_CART_REQUEST';
export const ALL_CART_SUCCESS = 'ALL_CART_SUCCESS';
export const ALL_CART_FAIL = 'ALL_CART_FAIL';

export const POST_CART = 'POST_CART';
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const ORDER_POST_REQUEST = 'ORDER_GET_REQUEST';
export const ORDER_GET_REQUEST = 'ORDER_GET_REQUEST';
export const ORDER_REQUEST_SUCCESS = 'ORDER_REQUEST_SUCCESS';
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS';
export const ORDER_REQUEST_FAIL = 'ORDER_REQUEST_FAIL';
export const CART_DETAIL_REQUEST = 'CART_DETAIL_REQUEST,';
export const CART_DETAIL_SUCCESS = 'CART_DETAIL_SUCCESS,';

export const SERVER = 'http://localhost:5000';
