const Province = [
    {
        "An Giang": [
            "Thành phố Long Xuyên",
            "Thành phố Châu Đốc",
            "Huyện An Phú",
            "Thị xã Tân Châu",
            "Huyện Phú Tân",
            "Huyện Châu Phú",
            "Huyện Tịnh Biên",
            "Huyện Tri Tôn",
            "Huyện Châu Thành",
            "Huyện Chợ Mới",
            "Huyện Thoại Sơn",
        ],
    },

    {
        "Bà rịa – Vũng tàu": [
            "Thành phố Vũng Tàu",
            "Thành phố Bà Rịa",
            "Huyện Châu Đức",
            "Huyện Xuyên Mộc",
            "Huyện Long Điền",
            "Huyện Đất Đỏ",
            "Huyện Tân Thành",
        ],
    },

    {
        "Bắc Giang": [
            "Huyện Hiệp Hòa",
            "Huyện Lạng Giang",
            "Huyện Lục Nam",
            "Huyện Lục Ngạn",
            "Huyện Sơn Động",
            "Huyện Tân Yên",
            "Huyện Việt Yên",
            "Huyện Yên Dũng",
            "Huyện Yên Thế",
            "Thành Phố Bắc Giang",
        ],
    },

    {
        "Bắc Kạn": [
            "Huyện Ba Bể",
            "Huyện Bạch Thông",
            "Huyện Chợ Mới",
            "Huyện Chợ Đồn",
            "Huyện Na Rì",
            "Huyện Ngân Sơn",
            "Huyện Pắc Nặm",
            "Thành Phố Bắc Kạn",
        ],
    },

    {
        "Bạc Liêu": [
            "Huyện Hòa Bình",
            "Huyện Hồng Dân",
            "Huyện Phước Long",
            "Huyện Vĩnh Lợi",
            "Huyện Đông Hải",
            "Thành Phố Bạc Liêu",
            "Thị Xã Giá Rai",
        ],
    },

    {
        "Bắc Ninh": [
            "Huyện Gia Bình",
            "Huyện Lương Tài",
            "Huyện Quế Võ",
            "Huyện Thuận Thành",
            "Huyện Tiên Du",
            "Huyện Yên Phong",
            "Thành Phố Bắc Ninh",
            "Thị Xã Từ Sơn",
        ],
    },

    {
        "Bến Tre": [
            "Huyện Ba Tri",
            "Huyện Bình Đại",
            "Huyện Châu Thành",
            "Huyện Chợ Lách",
            "Huyện Giồng Trôm",
            "Huyện Mỏ Cày Bắc",
            "Huyện Mỏ Cày Nam",
            "Huyện Thạnh Phú",
            "Thành Phố Bến Tre",
        ],
    },

    {
        "Bình Định": [
            "Huyện Bắc Bình",
            "Huyện Hàm Tân",
            "Huyện Hàm Thuận Bắc",
            "Huyện Hàm Thuận Nam",
            "Huyện Phú Quý",
            "Huyện Tánh Linh",
            "Huyện Tuy Phong",
            "Huyện Đức Linh",
            "Thành Phố Phan Thiết",
            "Thị Xã La Gi",
        ],
    },

    {
        "Bình Dương": [
            "Huyện Bắc Tân Uyên",
            "Huyện Bàu Bàng",
            "Huyện Dầu Tiếng",
            "Huyện Phú Giáo",
            "Thành Phố Dĩ An",
            "Thành Phố Thủ Dầu Một",
            "Thành Phố Thuận An",
            "Thị Xã Bến Cát",
            "Thị Xã Tân Uyên",
        ],
    },

    {
        "Bình Phước": [
            "Huyện Bù Gia Mập",
            "Huyện Bù Đăng",
            "Huyện Bù Đốp",
            "Huyện Chơn Thành",
            "Huyện Hớn Quản",
            "Huyện Lộc Ninh",
            "Huyện Phú Riềng",
            "Huyện Đồng Phú",
            "Thành Phố Đồng Xoài",
            "Thị Xã Bình Long",
            "Thị Xã Phước Long",
        ],
    },

    {
        "Bình Thuận": [
            "Huyện Bắc Bình",
            "Huyện Hàm Tân",
            "Huyện Hàm Thuận Bắc",
            "Huyện Hàm Thuận Nam",
            "Huyện Phú Quý",
            "Huyện Tánh Linh",
            "Huyện Tuy Phong",
            "Huyện Đức Linh",
            "Thành Phố Phan Thiết",
            "Thị Xã La Gi",
        ],
    },

    {
        "Cà Mau": [
            "Huyện Cái Nước",
            "Huyện Năm Căn",
            "Huyện Ngọc Hiển",
            "Huyện Phú Tân",
            "Huyện Thới Bình",
            "Huyện Trần Văn Thời",
            "Huyện U Minh",
            "Huyện Đầm Dơi",
            "Thành Phố Cà Mau",
        ],
    },

    {
        "Cần Thơ": [
            "Huyện Cờ Đỏ",
            "Huyện Phong Điền",
            "Huyện Phụng Hiệp",
            "Huyện Thới Lai",
            "Huyện Vĩnh Thạnh",
            "Quận Bình Thủy",
            "Quận Cái Răng",
            "Quận Ninh Kiều",
            "Quận Ô Môn",
            "Quận Thốt Nốt",
            "Thị Xã Ngã Bảy",
        ],
    },

    {
        "Cao Bằng ": [
            "Huyện Bảo Lạc",
            "Huyện Bảo Lâm",
            "Huyện Hạ Lang",
            "Huyện Hà Quảng",
            "Huyện Hòa An",
            "Huyện Nguyên Bình",
            "Huyện Quảng Hòa",
            "Huyện Thạch An",
            "Huyện Trùng Khánh",
            "Thành Phố Cao Bằng",
        ],
    },

    {
        "Đà Nẵng": [
            "Huyện Hòa Vang",
            "Huyện Hoàng Sa",
            "Quận Cẩm Lệ",
            "Quận Hải Châu",
            "Quận Liên Chiểu",
            "Quận Ngũ Hành Sơn",
            "Quận Sơn Trà",
            "Quận Thanh Khê",
            "Thị Xã Điện Bàn",
        ],
    },

    {
        "Đắk Lắk": [
            "Huyện Buôn Đôn",
            "Huyện Cư Kuin",
            "Huyện Cư M'Gar",
            "Huyện Ea H'Leo",
            "Huyện Ea Kar",
            "Huyện Ea Súp",
            "Huyện Krông A Na",
            "Huyện Krông Bông",
            "Huyện Krông Búk",
            "Huyện Krông Năng",
            "Huyện Krông Pắk",
            "Huyện Lắk",
            "Huyện M'Đrắk",
            "Thành Phố Buôn Ma Thuột",
            "Thị Xã Buôn Hồ",
        ],
    },

    {
        "Đắk Nông": [
            "Huyện Cư Jút",
            "Huyện Krông Nô",
            "Huyện Tuy Đức",
            "Huyện Đắk Glong",
            "Huyện Đắk Mil",
            "Huyện Đắk R'Lấp",
            "Huyện Đắk Song",
            "Thị Xã Gia Nghĩa",
        ],
    },

    {
        "Điện Biên": [
            "Huyện Mường Ảng",
            "Huyện Mường Chà",
            "Huyện Mường Nhé",
            "Huyện Nậm Pồ",
            "Huyện Tủa Chùa",
            "Huyện Tuần Giáo",
            "Huyện Điện Biên",
            "Huyện Điện Biên Đông",
            "Thành Phố Điện Biên Phủ",
            "Thị Xã Mường Lay",
        ],
    },

    {
        "Đồng Nai": [
            "Huyện Cẩm Mỹ",
            "Huyện Long Thành",
            "Huyện Nhơn Trạch",
            "Huyện Tân Phú",
            "Huyện Thống Nhất",
            "Huyện Trảng Bom",
            "Huyện Vĩnh Cửu",
            "Huyện Xuân Lộc",
            "Huyện Định Quán",
            "Thành Phố Biên Hòa",
            "Thành Phố Long Khánh",
        ],
    },

    {
        "Đồng Tháp": [
            "Huyện Cao Lãnh",
            "Huyện Châu Thành",
            "Huyện Hồng Ngự",
            "Huyện Lai Vung",
            "Huyện Lấp Vò",
            "Huyện Tam Nông",
            "Huyện Tân Hồng",
            "Huyện Thanh Bình",
            "Huyện Tháp Mười",
            "Thành Phố Cao Lãnh",
            "Thành Phố Sa Đéc",
            "Thị Xã Hồng Ngự",
        ],
    },

    {
        "Gia Lai": [
            "Huyện Chư Păh",
            "Huyện Chư Prông",
            "Huyện Chư Pưh",
            "Huyện Chư Sê",
            "Huyện Ia Grai",
            "Huyện Ia Pa",
            "Huyện Kbang",
            "Huyện Kông Chro",
            "Huyện Krông Pa",
            "Huyện Mang Yang",
            "Huyện Phú Thiện",
            "Huyện Đăk Pơ",
            "Huyện Đăk Đoa",
            "Huyện Đức Cơ",
            "Thành Phố Pleiku",
            "Thị Xã An Khê",
            "Thị Xã Ayun Pa",
        ],
    },

    {
        "Hà Giang": [
            "Huyện Bắc Mê",
            "Huyện Bắc Quang",
            "Huyện Hoàng Su Phì",
            "Huyện Mèo Vạc",
            "Huyện Quản Bạ",
            "Huyện Quang Bình",
            "Huyện Vị Xuyên",
            "Huyện Xín Mần",
            "Huyện Yên Minh",
            "Huyện Đồng Văn",
            "Thành Phố Hà Giang",
        ],
    },

    {
        "Hà Nam": [
            "Huyện Bình Lục",
            "Huyện Kim Bảng",
            "Huyện Lý Nhân",
            "Huyện Thanh Liêm",
            "Thành Phố Phủ Lý",
            "Thị Xã Duy Tiên",
        ],
    },

    {
        "Hà Nội ": [
            "Quận Ba Đình",
            "Quận Hoàn Kiếm",
            "Quận Tây Hồ",
            "Quận Long Biên",
            "Quận Cầu Giấy",
            "Quận Đống Đa",
            "Quận Hai Bà Trưng",
            "Quận Hoàng Mai",
            "Quận Thanh Xuân",
            "Huyện Sóc Sơn",
            "Huyện Đông Anh",
            "Huyện Gia Lâm",
            "Quận Nam Từ Liêm",
            "Huyện Thanh Trì",
            "Quận Bắc Từ Liêm",
            "Huyện Mê Linh",
            "Quận Hà Đông",
            "Thị xã Sơn Tây",
            "Huyện Ba Vì",
            "Huyện Phúc Thọ",
            "Huyện Đan Phượng",
            "Huyện Hoài Đức",
            "Huyện Quốc Oai",
            "Huyện Thạch Thất",
            "Huyện Chương Mỹ",
            "Huyện Thanh Oai",
            "Huyện Thường Tín",
            "Huyện Phú Xuyên",
            "Huyện Ứng Hòa",
            "Huyện Mỹ Đức",
        ],
    },

    {
        "Hà Tĩnh": [
            "Huyện Cẩm Xuyên",
            "Huyện Can Lộc",
            "Huyện Hương Khê",
            "Huyện Hương Sơn",
            "Huyện Kỳ Anh",
            "Huyện Lộc Hà",
            "Huyện Nghi Xuân",
            "Huyện Thạch Hà",
            "Huyện Vũ Quang",
            "Huyện Đức Thọ",
            "Thành Phố Hà Tĩnh",
            "Thị Xã Hồng Lĩnh",
            "Thị Xã Kỳ Anh",
        ],
    },

    {
        "Hải Dương": [
            "Huyện Bình Giang",
            "Huyện Cẩm Giàng",
            "Huyện Gia Lộc",
            "Huyện Kim Thành",
            "Huyện Nam Sách",
            "Huyện Ninh Giang",
            "Huyện Thanh Hà",
            "Huyện Thanh Miện",
            "Huyện Tứ Kỳ",
            "Thành Phố Chí Linh",
            "Thành Phố Hải Dương",
            "Thị Xã Kinh Môn",
        ],
    },

    {
        "Hải Phòng": [
            "Huyện An Dương",
            "Huyện An Lão",
            "Huyện Kiến Thụy",
            "Huyện Thủy Nguyên",
            "Huyện Tiên Lãng",
            "Huyện Vĩnh Bảo",
            "Huyện Đảo Bạch Long Vĩ",
            "Huyện Đảo Cát Hải",
            "Quận Dương Kinh",
            "Quận Hải An",
            "Quận Hồng Bàng",
            "Quận Kiến An",
            "Quận Lê Chân",
            "Quận Ngô Quyền",
            "Quận Đồ Sơn",
        ],
    },

    {
        "Hậu Giang": [
            "Huyện Châu Thành",
            "Huyện Châu Thành A",
            "Huyện Long Mỹ",
            "Huyện Phụng Hiệp",
            "Huyện Vị Thủy",
            "Thành Phố Ngã Bảy",
            "Thành Phố Vị Thanh",
            "Thị Xã Long Mỹ",
        ],
    },

    {
        "Hòa Bình": [
            "Huyện Cao Phong",
            "Huyện Kim Bôi",
            "Huyện Kỳ Sơn",
            "Huyện Lạc Sơn",
            "Huyện Lạc Thủy",
            "Huyện Lương Sơn",
            "Huyện Mai Châu",
            "Huyện Tân Lạc",
            "Huyện Yên Thủy",
            "Huyện Đà Bắc",
            "Thành Phố Hòa Bình",
        ],
    },

    {
        "Hưng Yên": [
            "Huyện Ân Thi",
            "Huyện Khoái Châu",
            "Huyện Kim Động",
            "Huyện Phù Cừ",
            "Huyện Tiên Lữ",
            "Huyện Văn Giang",
            "Huyện Văn Lâm",
            "Huyện Yên Mỹ",
            "Thành Phố Hưng Yên",
            "Thị Xã Mỹ Hào",
        ],
    },

    {
        "Khánh Hòa": [
            "Huyện Cam Lâm",
            "Huyện Diên Khánh",
            "Huyện Khánh Sơn",
            "Huyện Khánh Vĩnh",
            "Huyện Trường Sa",
            "Huyện Vạn Ninh",
            "Thành Phố Cam Ranh",
            "Thành Phố Nha Trang",
            "Thị Xã Ninh Hòa",
        ],
    },

    {
        "Kiên Giang": [
            "Huyện An Biên",
            "Huyện An Minh",
            "Huyện Châu Thành",
            "Huyện Giang Thành",
            "Huyện Giồng Riềng",
            "Huyện Gò Quao",
            "Huyện Hòn Đất",
            "Huyện Kiên Hải",
            "Huyện Kiên Lương",
            "Huyện Tân Hiệp",
            "Huyện U Minh Thượng",
            "Huyện Vĩnh Thuận",
            "Thành Phố Hà Tiên",
            "Thành Phố Phú Quốc",
            "Thành Phố Rạch Giá",
        ],
    },

    {
        "Kon Tum": [
            "Huyện Ia H' Drai",
            "Huyện Kon Plông",
            "Huyện Kon Rẫy",
            "Huyện Ngọc Hồi",
            "Huyện Sa Thầy",
            "Huyện Tu Mơ Rông",
            "Huyện Đắk Glei",
            "Huyện Đắk Hà",
            "Huyện Đắk Tô",
            "Thành Phố Kon Tum",
        ],
    },

    {
        "Lai Châu": [
            "Huyện Mường Tè",
            "Huyện Nậm Nhùn",
            "Huyện Phong Thổ",
            "Huyện Sìn Hồ",
            "Huyện Tam Đường",
            "Huyện Tân Uyên",
            "Huyện Than Uyên",
            "Thành Phố Lai Châu",
        ],
    },

    {
        "Lâm Đồng": [
            "Huyện Bảo Lâm",
            "Huyện Cát Tiên",
            "Huyện Di Linh",
            "Huyện Lạc Dương",
            "Huyện Lâm Hà",
            "Huyện Đạ Huoai",
            "Huyện Đạ Tẻh",
            "Huyện Đam Rông",
            "Huyện Đơn Dương",
            "Huyện Đức Trọng",
            "Thành Phố Bảo Lộc",
            "Thành Phố Đà Lạt",
        ],
    },

    {
        "Lạng Sơn": [
            "Huyện Bắc Sơn",
            "Huyện Bình Gia",
            "Huyện Cao Lộc",
            "Huyện Chi Lăng",
            "Huyện Hữu Lũng",
            "Huyện Lộc Bình",
            "Huyện Tràng Định",
            "Huyện Văn Lãng",
            "Huyện Văn Quan",
            "Huyện Đình Lập",
            "Thành Phố Lạng Sơn",
        ],
    },

    {
        "Lào Cai": [
            "Huyện Bắc Hà",
            "Huyện Bảo Thắng",
            "Huyện Bảo Yên",
            "Huyện Bát Xát",
            "Huyện Mường Khương",
            "Huyện Si Ma Cai",
            "Huyện Văn Bàn",
            "Thành Phố Lào Cai",
            "Thị Xã Sa Pa",
        ],
    },

    {
        "Long An": [
            "Thành phố Tân An",
            "Thị xã Kiến Tường",
            "Huyện Tân Hưng",
            "Huyện Vĩnh Hưng",
            "Huyện Mộc Hóa",
            "Huyện Tân Thạnh",
            "Huyện Thạnh Hóa",
            "Huyện Đức Huệ",
            "Huyện Đức Hòa",
            "Huyện Bến Lức",
            "Huyện Thủ Thừa",
            "Huyện Tân Trụ",
            "Huyện Cần Đước",
            "Huyện Cần Giuộc",
            "Huyện Châu Thành",
        ],
    },

    {
        "Nam Định": [
            "Huyện Giao Thủy",
            "Huyện Hải Hậu",
            "Huyện Mỹ Lộc",
            "Huyện Nam Trực",
            "Huyện Nghĩa Hưng",
            "Huyện Trực Ninh",
            "Huyện Vụ Bản",
            "Huyện Xuân Trường",
            "Huyện Ý Yên",
            "Thành Phố Nam Định",
        ],
    },

    {
        "Nghệ An": [
            "Huyện Anh Sơn",
            "Huyện Con Cuông",
            "Huyện Diễn Châu",
            "Huyện Hưng Nguyên",
            "Huyện Kỳ Sơn",
            "Huyện Nam Đàn",
            "Huyện Nghi Lộc",
            "Huyện Nghĩa Đàn",
            "Huyện Quế Phong",
            "Huyện Quỳ Châu",
            "Huyện Quỳ Hợp",
            "Huyện Quỳnh Lưu",
            "Huyện Tân Kỳ",
            "Huyện Thanh Chương",
            "Huyện Tương Dương",
            "Huyện Yên Thành",
            "Huyện Đô Lương",
            "Thành Phố Vinh",
            "Thị Xã Cửa Lò",
            "Thị Xã Hoàng Mai",
            "Thị Xã Thái Hòa",
        ],
    },

    {
        "Ninh Bình": [
            "Huyện Gia Viễn",
            "Huyện Hoa Lư",
            "Huyện Kim Sơn",
            "Huyện Nho Quan",
            "Huyện Yên Khánh",
            "Huyện Yên Mô",
            "Thành Phố Ninh Bình",
            "Thành Phố Tam Điệp",
        ],
    },

    {
        "Ninh Thuận": [
            "Huyện Bác Ái",
            "Huyện Ninh Hải",
            "Huyện Ninh Phước",
            "Huyện Ninh Sơn",
            "Huyện Thuận Bắc",
            "Huyện Thuận Nam",
            "Thành Phố Phan Rang-Tháp Chàm",
        ],
    },

    {
        "Phú Thọ": [
            "Huyện Cẩm Khê",
            "Huyện Hạ Hòa",
            "Huyện Lâm Thao",
            "Huyện Phù Ninh",
            "Huyện Tam Nông",
            "Huyện Tân Sơn",
            "Huyện Thanh Ba",
            "Huyện Thanh Sơn",
            "Huyện Thanh Thủy",
            "Huyện Yên Lập",
            "Huyện Đoan Hùng",
            "Thành Phố Việt Trì",
            "Thị Xã Phú Thọ",
        ],
    },

    {
        "Phú Yên": [
            "Huyện Phú Hòa",
            "Huyện Sơn Hòa",
            "Huyện Sông Hinh",
            "Huyện Tây Hòa",
            "Huyện Tuy An",
            "Huyện Đồng Xuân",
            "Thành Phố Tuy Hòa",
            "Thị Xã Sông Cầu",
            "Thị Xã Đông Hòa",
        ],
    },

    {
        "Quảng Bình": [
            "Huyện Bố Trạch",
            "Huyện Lệ Thủy",
            "Huyện Minh Hóa",
            "Huyện Quảng Ninh",
            "Huyện Quảng Trạch",
            "Huyện Tuyên Hóa",
            "Thành Phố Đồng Hới",
            "Thị Xã Ba Đồn",
        ],
    },

    {
        "Quảng Nam": [
            "Huyện Bắc Trà My",
            "Huyện Duy Xuyên",
            "Huyện Hiệp Đức",
            "Huyện Nam Giang",
            "Huyện Nam Trà My",
            "Huyện Nông Sơn",
            "Huyện Núi Thành",
            "Huyện Phú Ninh",
            "Huyện Phước Sơn",
            "Huyện Quế Sơn",
            "Huyện Tây Giang",
            "Huyện Thăng Bình",
            "Huyện Tiên Phước",
            "Huyện Đại Lộc",
            "Huyện Đông Giang",
            "Thành Phố Hội An",
            "Thành Phố Tam Kỳ",
            "Thị Xã Điện Bàn",
        ],
    },

    {
        "Quảng Ngãi": [
            "Huyện Ba Tơ",
            "Huyện Bình Sơn",
            "Huyện Lý Sơn",
            "Huyện Minh Long",
            "Huyện Mộ Đức",
            "Huyện Nghĩa Hành",
            "Huyện Sơn Hà",
            "Huyện Sơn Tây",
            "Huyện Sơn Tịnh",
            "Huyện Trà Bồng",
            "Huyện Tư Nghĩa",
            "Thành Phố Quảng Ngãi",
            "Thị Xã Đức Phổ",
        ],
    },

    {
        "Quảng Ninh": [
            "Huyện Ba Chẽ",
            "Huyện Bình Liêu",
            "Huyện Cô Tô",
            "Huyện Hải Hà",
            "Huyện Tiên Yên",
            "Huyện Vân Đồn",
            "Huyện Đầm Hà",
            "Thành Phố Cẩm Phả",
            "Thành Phố Hạ Long",
            "Thành Phố Móng Cái",
            "Thành Phố Uông Bí",
            "Thị Xã Quảng Yên",
            "Thị Xã Đông Triều",
        ],
    },

    {
        "Quảng Trị": [
            "Huyện Cam Lộ",
            "Huyện Cồn Cỏ",
            "Huyện Gio Linh",
            "Huyện Hải Lăng",
            "Huyện Hướng Hóa",
            "Huyện Triệu Phong",
            "Huyện Vĩnh Linh",
            "Huyện Đa Krông",
            "Thành Phố Đông Hà",
            "Thị Xã Quảng Trị",
        ],
    },

    {
        "Sóc Trăng": [
            "Huyện Châu Thành",
            "Huyện Cù Lao Dung",
            "Huyện Kế Sách",
            "Huyện Long Phú",
            "Huyện Mỹ Tú",
            "Huyện Mỹ Xuyên",
            "Huyện Thạnh Trị",
            "Huyện Trần Đề",
            "Thành Phố Sóc Trăng",
            "Thị Xã Ngã Năm",
            "Thị Xã Vĩnh Châu",
        ],
    },

    {
        "Sơn La": [
            "Huyện Bắc Yên",
            "Huyện Mai Sơn",
            "Huyện Mộc Châu",
            "Huyện Mường La",
            "Huyện Phù Yên",
            "Huyện Quỳnh Nhai",
            "Huyện Sông Mã",
            "Huyện Sốp Cộp",
            "Huyện Thuận Châu",
            "Huyện Vân Hồ",
            "Huyện Yên Châu",
            "Thành Phố Sơn La",
        ],
    },

    {
        "Tây Ninh": [
            "Huyện Bến Cầu",
            "Huyện Châu Thành",
            "Huyện Dương Minh Châu",
            "Huyện Gò Dầu",
            "Huyện Tân Biên",
            "Huyện Tân Châu",
            "Thành Phố Tây Ninh",
            "Thị Xã Hòa Thành",
            "Thị Xã Trảng Bàng",
        ],
    },

    {
        "Thái Bình": [
            "Huyện Hưng Hà",
            "Huyện Kiến Xương",
            "Huyện Quỳnh Côi",
            "Huyện Quỳnh Phụ",
            "Huyện Thái Thụy",
            "Huyện Tiền Hải",
            "Huyện Vũ Thư",
            "Huyện Đông Hưng",
            "Thành Phố Thái Bình",
        ],
    },

    {
        "Thái Nguyên": [
            "Huyện Phú Bình",
            "Huyện Phú Lương",
            "Huyện Võ Nhai",
            "Huyện Đại Từ",
            "Huyện Định Hóa",
            "Huyện Đồng Hỷ",
            "Thành Phố Sông Công",
            "Thành Phố Thái Nguyên",
            "Thị Xã Phổ Yên",
        ],
    },

    {
        "Thanh Hóa": [
            "Huyện Bá Thước",
            "Huyện Cẩm Thủy",
            "Huyện Hà Trung",
            "Huyện Hậu Lộc",
            "Huyện Hoằng Hóa",
            "Huyện Lang Chánh",
            "Huyện Mường Lát",
            "Huyện Nga Sơn",
            "Huyện Ngọc Lặc",
            "Huyện Như Thanh",
            "Huyện Như Xuân",
            "Huyện Nông Cống",
            "Huyện Quan Hóa",
            "Huyện Quan Sơn",
            "Huyện Quảng Xương",
            "Huyện Thạch Thành",
            "Huyện Thiệu Hóa",
            "Huyện Thọ Xuân",
            "Huyện Thường Xuân",
            "Huyện Triệu Sơn",
            "Huyện Vĩnh Lộc",
            "Huyện Yên Định",
            "Huyện Đông Sơn",
            "Thành Phố Sầm Sơn",
            "Thành Phố Thanh Hóa",
            "Thị Xã Bỉm Sơn",
            "Thị Xã Nghi Sơn",
        ],
    },

    {
        "Thừa Thiên Huế": [
            "Huyện A Lưới",
            "Huyện Nam Đông",
            "Huyện Phong Điền",
            "Huyện Phú Lộc",
            "Huyện Phú Vang",
            "Huyện Quảng Điền",
            "Thành Phố Huế",
            "Thị Xã Hương Thủy",
            "Thị Xã Hương Trà",
        ],
    },

    {
        "Tiền Giang": [
            "Huyện Cái Bè",
            "Huyện Cai Lậy",
            "Huyện Châu Thành",
            "Huyện Chợ Gạo",
            "Huyện Gò Công Tây",
            "Huyện Gò Công Đông",
            "Huyện Tân Phú Đông",
            "Huyện Tân Phước",
            "Thành Phố Mỹ Tho",
            "Thị Xã Cai Lậy",
            "Thị Xã Gò Công",
        ],
    },

    {
        "Thành phố Hồ Chí Minh": [
            "Quận 1",
            "Quận 12",
            "Quận Thủ Đức",
            "Quận 9",
            "Quận Gò Vấp",
            "Quận Bình Thạnh",
            "Quận Tân Bình",
            "Quận Tân Phú",
            "Quận Phú Nhuận",
            "Quận 2",
            "Quận 3",
            "Quận 10",
            "Quận 11",
            "Quận 4",
            "Quận 5",
            "Quận 6",
            "Quận 8",
            "Quận Bình Tân",
            "Quận 7",
            "Huyện Củ Chi",
            "Huyện Hóc Môn",
            "Huyện Bình Chánh",
            "Huyện Nhà Bè",
            "Huyện Cần Giờ",
        ],
    },

    {
        "Trà Vinh": [
            "Huyện Càng Long",
            "Huyện Cầu Kè",
            "Huyện Cầu Ngang",
            "Huyện Châu Thành",
            "Huyện Duyên Hải",
            "Huyện Tiểu Cần",
            "Huyện Trà Cú",
            "Thành Phố Trà Vinh",
            "Thị Xã Duyên Hải",
        ],
    },

    {
        "Tuyên Quang": [
            "Huyện Chiêm Hóa",
            "Huyện Hàm Yên",
            "Huyện Lâm Bình",
            "Huyện Na Hang",
            "Huyện Sơn Dương",
            "Huyện Yên Sơn",
            "Thành Phố Tuyên Quang",
        ],
    },

    {
        "Vĩnh Long": [
            "Huyện Bình Tân",
            "Huyện Long Hồ",
            "Huyện Mang Thít",
            "Huyện Tam Bình",
            "Huyện Trà Ôn",
            "Huyện Vũng Liêm",
            "Thành Phố Vĩnh Long",
            "Thị Xã Bình Minh",
        ],
    },

    {
        "Vĩnh Phúc": [
            "Huyện Bình Xuyên",
            "Huyện Lập Thạch",
            "Huyện Sông Lô",
            "Huyện Tam Dương",
            "Huyện Tam Đảo",
            "Huyện Vĩnh Tường",
            "Huyện Yên Lạc",
            "Thành Phố Phúc Yên",
            "Thành Phố Vĩnh Yên",
        ],
    },

    {
        "Yên Bái": [
            "Huyện Lục Yên",
            "Huyện Mù Căng Chải",
            "Huyện Trạm Tấu",
            "Huyện Trấn Yên",
            "Huyện Văn Chấn",
            "Huyện Văn Yên",
            "Huyện Yên Bình",
            "Thành Phố Yên Bái",
            "Thị Xã Nghĩa Lộ",
        ],
    },
];

export default Province;
