export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_REQUEST';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPLOAD_PROFILE = 'USER_UPLOAD_PROFILE';
export const USER_UPLOAD_REQUEST = 'USER_UPLOAD_REQUEST';
export const USER_VERIFY = 'USER_VERIFY';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_FORGET_SENDEMAIL = 'USER_FORGET_SENDEMAIL';
export const USER_FORGET_RESET = 'USER_FORGET_RESET';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const SET_REFRESH_TOKEN_ID = 'SET_REFRESH_TOKEN_ID';

export const ACCESSTOKEN = 'ACCESSTOKEN';
